INSERT INTO `items` (`item_id`, `name`, `description`, `cmd`, `image`, `do`, ``, ``, ``, ``) VALUES
(`it_01`, `Messenger Bag`, `A vintage messenger bag with a max capacity of 15 items.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_02`, `Spare Key`, `A spare key attached to a large gold key ring.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_03`, `Book`, `A hard cover book titled "The Cure to Transitioning". It is the missing book!`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_04`, `Holy Water`, `A small glass vial in the shape of a cross containing holy water.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_05`, `Vial of Scales`, `A small glass vial containing blue scales.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_06`, `Red Silk Rose`, `A long silk red rose.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_07`, `Dracula's Blood`, `Crimson red, flowy, and still luke warm. It smells metalic!  `, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_08`, `Flask`, `A stainless steal flask with mirror finish.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_09`, `Black Gem`, `A black gem that fits perfectly in the palm of your hand.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_10`, `Mortar and Pestle`, `A stainless steel mortar and pestle with grey marble finish. `, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_11`, `Hint Token`, `Hint tokens. Very useful in providing clues to solving a puzzles.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_12`, `Monster Coin`, `An antique monster coin. What a beauty.`, `cmd`, `image`, `do`, `5`, ``, ``, ``);
(`it_13`, `Cookie`, `Fresh, warm cookies that can recover your health.`, `cmd`, `image`, `do`, `20`, ``, ``, ``);
(`it_14`, `Cheese and Crackers`, `Cheese and crackers. Finally some snacks.`, `cmd`, `image`, `do`, ``, ``, ``, ``);
(`it_15`, `Cleaver`, `A cleaver- SCREECH SCREECH SCREECH SCREECH SCREECH`, `cmd`, `image`, `do`, ``, `2`, ``, ``);
(`it_16`, `Hook`, `Captain Backbeard's hook.`, `cmd`, `image`, `do`, ``, `4`, ``, ``);
(`it_17`, `Swiss Knife`, `A swiss knife used to cut the cheese`, `cmd`, `image`, `do`, ``, `1`, ``, ``);
(`it_18`, `Newspaper`, `Large newspaper all rolled up together. Stories about defeating vampires are in the palm of your hand.`, `cmd`, `image`, `do`, ``, `5`, ``, ``);
(`it_19`, `Extra-Long Wooden Stake`, `Some would just call it a "wooden-sword". Looks who's still fighting vampires!`, `cmd`, `image`, `do`, ``, `2`, `20`, ``);
(`it_20`, `Garlic`, `A garlic so strong, its smell is making you tear up. A rather unusual weapon for fighting vampires!`, `cmd`, `image`, `do`, ``, `2`, `10`, ``);
(`it_21`, `Crossbow`, `The highest quality crossbow you've ever seen. It was made by the werewolf merchant himself! The arrows are made of Extra-Long Wooden Stake.`, `cmd`, `image`, `do`, ``, `8`, `25`, ``);
(`it_22`, `Leather Boots`, `Black leather boots that provides protection. Great for mosh pits.`, `cmd`, `image`, `do`, ``, ``, ``, `2`);
(`it_23`, `Leather Jacket`, `A thick leather jacket that provides protection, complete with patches from asserted mosh pits`, `cmd`, `image`, `do`, ``, ``, ``, `3`);
(`it_24`, `Scarf`, `A cosy winter scarf. It doesn't provide much protection, but it keeps the cold away.`, `cmd`, `image`, `do`, ``, ``, ``, `1`);
(`it_25`, `Knight Helm`, `A sturdy, silver knight helm that provides protection`, `cmd`, `image`, `do`, ``, ``, ``, `5`);
(`it_26`, `Bullet Proof Vest`, `A bullet proof vest perfect for a stroll in the bad part of town!`, `cmd`, `image`, `do`, ``, ``, ``, `4`);
(`it_27`, `Red Hat`, `A red hat stainedeth with the blood of thy enemies`, `cmd`, `image`, `do`, ``, ``, ``, `1`);
(`it_28`, `Gloves of the Pugilist`, `The gloves of the pugilist. Warm, waterproof, soft, unique, and it comes in a pair!`, `cmd`, `image`, `do`, ``, ``, ``, `5`);
